### ISSUE TITLE
Not all found items in PaB are available to transfer to basket 

### ISSUE THREAD

**Issue by aawsum** [BrickTwo/BrickHunter#201]
As an example, I have abricklink partslist of 6 items. 
1 is not found, 3 are bestseller, 2 are standard.
They are visible on the "all" page.

However the tab "bestseller" only shows 2 and the tab "standard" only shows 1.
Same in the shopping list.
It is a bit strange.

![image](https://github.com/BrickTwo/BrickHunter/assets/141509067/549e47bb-14cd-49a4-bfa9-f90950cc2f9c)

**Comment by aawsum** [comment]
Maybe one additional thing here, why are the PaB prices not shown in the normal overview. They are shown if you do an export but not in the screen as visible in above screenprint.

**Comment by BrickTwo** [comment]
Issue "missing part in Standard tab":
- That's because BrickHunter checks per default the PaB price against the BrickHunter price (if available). You can change this behavior under the settings button on the right.

Issue "price not shown":
- that's indeed a good question. Can you maybe check if the language/country settings in the BrickHunter Settings are set correctly. Maybe also change it to something else and then go back to the correct one and then check again if the prices are still missing.

**Comment by aawsum** [comment]
Ok if I check the setting "Ignore BrickLink prices" then indeed all parts are now added to the pab tabs correctly.

For the missing price,well I had Netherlands/Dutch.
I changed to Netherlands/English, German/german, German/English and resynched every time but pricesare not showing for PaB in the screen. If I export to for example a pdf prices are showing.

**Comment by BrickTwo** [comment]
Which version of BrickHunter is installed and which Browser are you using?
